### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Demarsch** [Demarsch/gun-violence-dashboard#22]
- [x] Extract x-axis and z-axis data from DB and join it with regular data
- [x] Add configuration of widget header
- [x] Add filter by state
- [x] Add filter by year
- [x] Return 'Male'/ 'Female' for gender
- [x] Add 'Top'/'Bottom' limits _(N/A, not sure what to do with multipivots)_
- [x] Add extra statistics
- [x] Scrape incident list from gun-violence archive
- [x] Restyle check buttons
- [x] Add large 'Add Widget' button if there are no widgets yet
- [x] Sunburst chart OR x-y pivot chart
